# Generated by Django 6.0.3 on 2026-05-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_placedstudent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placedstudent',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Placed Student', 'verbose_name_plural': 'Placed Students'},
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
