# Generated by Django 5.2.14 on 2026-05-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('slug', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=5.0)),
                ('image', models.ImageField(upload_to='courses/')),
                ('highlights', models.JSONField(default=list)),
                ('category', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True, null=True)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('syllabus', models.JSONField(blank=True, default=list)),
                ('instructors', models.JSONField(blank=True, default=list)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
