# Generated by Django 6.0.3 on 2026-10-05 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedstudent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='position',
        ),
    ]
