# Generated by Django 6.0.3 on 2026-10-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_placedstudent_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.AddField(
            model_name='course',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
