# Generated by Django 6.0.3 on 2026-10-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_course_instructors_remove_course_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
    ]
