# Generated by Django 6.0.3 on 2026-10-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses_teaching', to='api.trainer'),
        ),
    ]
