# Generated by Django 6.0.3 on 2026-10-09 17:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brochure',
            field=models.FileField(blank=True, null=True, storage=api.models.get_raw_storage, upload_to='brochures/', validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(storage=api.models.get_raw_storage, upload_to='resumes/', validators=[api.models.validate_file_size]),
        ),
    ]
